#!/bin/bash
# run as root

IFACE=$1 # eth0
MAC=$2 # 55:55:55:55:55:55

if [ $(id -u) -ne 0 ]
  then
  echo "ERROR: Run as Root; Aborting"
  exit
fi

# assumes this does not exist!
CONFIG_FILE="/etc/udev/rules.d/70-persistent-net.rules"

echo "Creating and writing $CONFIG_FILE"
printf \
"SUBSYSTEM==\"net\", ACTION==\"add\", ATTR{address}==\"$MAC\", NAME=\"$IFACE\"" \
>> $CONFIG_FILE

echo "On next reboot NIC should have name $IFACE with MAC $MAC"
