#!/bin/bash
# run as root
# Assumes fresh minimal install of centos7 and that networking was configured during the install

if [ $(id -u) -ne 0 ]
  then
  echo "ERROR: Run as Root; Aborting"
  exit
fi

echo "Running yum update"
yum -y update
echo "Installing software"
yum -y install epel-release
yum -y install epel-release tmux vim wget epel-release net-tools unzip zip perl-Data-Dumper bind-utils # java java-devel gcc gpp
