#!/bin/bash
# run as root
# IMPORTANT: This will only allow ssh login with keys; configure authorized_keys beforehand

if [ $(id -u) -ne 0 ]
  then
  echo "ERROR: Run as Root; Aborting"
  exit
fi

CONFIG_FILE="/etc/ssh/sshd_config"
sed -c -i "s/\(PasswordAuthentication *  *\).*/\1no/" $CONFIG_FILE
printf "\n\n#Additional User Settings\n\
PermitRootLogin no">> $CONFIG_FILE
